spring:
  datasource:
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    url: jdbc:ucanaccess://C:\Users/user/Downloads/JavaAssignment/JavaAssignment/accountsdb.accdb

  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        dialect: net.ucanaccess.hibernate.dialect.UCanAccessDialect

logging:
  level:
    org:
      springframework : DEBUG

server:
  servlet:
    session:
      timeout: 300s
  port: 1111