spring:
  datasource:
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    url: jdbc:ucanaccess://C:\Users/user/Downloads/JavaAssignment/JavaAssignment/accountsdb.accdb

  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: com.tree.assignment.config.AccessPhysicalNamingStrategy
        hbm2ddl:
          auto: none
        tmp:
          use_jdbc_metadata_defaults: false
        ddl-auto: validate
        dialect: net.ucanaccess.hibernate.dialect.UCanAccessDialect




# H2 console configuration (optional)
#h2:
#  console:
#    enabled: true
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#  web:
#    allowed-origins: "*" # Configure this based on your security requirements

logging:
  level:
    org:
      springframework : DEBUG


server:
  servlet:
    session:
      timeout: 300s
  port: 1111

