spring:
# H2 console configuration (optional)
h2:
  console:
    enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
#  web:
#    allowed-origins: "*" # Configure this based on your security requirements

logging:
  level:
    org:
      springframework : INFO


server:
  servlet:
    session:
      timeout: 60s
  port: 1111

